version: '3.9' 

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rsc
    working_dir: /works
    volumes:
      - .:/works
      - node_modules:/works/node_modules
      - /var/run/docker.sock:/var/run/docker.sock\

volumes:
  node_modules: